# Generated by Django 5.1.2 on 2024-11-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('branch', models.CharField(choices=[('Mca', 'MCA'), ('Bph', 'Btech Pharmacy'), ('Bcse', 'Btech CSE'), ('Bit', 'Btech IT'), ('Bece', 'Btech ECE'), ('Mba', 'MBA')], max_length=4)),
            ],
        ),
    ]
