# Generated by Django 5.1.2 on 2024-11-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cankiet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_no', models.CharField(max_length=12)),
                ('item', models.CharField(max_length=20)),
                ('price', models.IntegerField(max_length=3)),
                ('c_no', models.CharField(max_length=12)),
                ('availability', models.CharField(max_length=1)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
