# Generated by Django 5.1.2 on 2024-11-25 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cankiet', '0003_alter_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='i_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/foods/'),
            preserve_default=False,
        ),
    ]
