# Generated by Django 5.1.2 on 2024-11-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cankiet', '0004_items_i_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('c_no', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='i_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
