# Generated by Django 5.1.2 on 2024-11-25 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cankiet', '0006_remove_items_id_remove_user_id_alter_items_i_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_no', models.AutoField(primary_key=True, serialize=False)),
                ('o_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_amount', models.IntegerField(default=0)),
                ('c_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cankiet.canteen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cankiet.items')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cankiet.user')),
            ],
        ),
    ]
