# Generated by Django 5.1.2 on 2024-11-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cankiet', '0008_remove_order_u_id_alter_order_o_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('R', 'rejected'), ('I', 'in-progress'), ('C', 'completed')], default='I', max_length=1),
        ),
    ]
