# Generated by Django 5.1.2 on 2024-11-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cankiet', '0009_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='i_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
