# Generated by Django 5.1.2 on 2024-11-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cankiet', '0011_alter_items_i_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='i_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
