# Generated by Django 5.1.2 on 2024-11-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cankiet', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Rejected', 'rejected'), ('In Progress', 'in-progress'), ('Compeleted', 'completed')], default='In Progress', max_length=11),
        ),
    ]
